[dev]
  command = "yarn dev" # Command to start your dev server
  port = 8888 # Port that the dev server will be listening on
  proxyPort = 3000
  publish = "static" # If you use a _redirect file, provide the path to your static content folder
